chore: fix concurrency execute with melos. (#563)
## What does this change?

I limited concurrent execution because these logs were being output
during the execution of the flutter command.

When `melos run get`
```
ERROR: ERROR: [example]: Waiting for another flutter command to release the startup lock...
ERROR: ERROR: [flutter_gen]: Waiting for another flutter command to release the startup lock...
ERROR: ERROR: [flutter_gen_runner]: Waiting for another flutter command to release the startup lock...
```

And fix analyze.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

Before submitting your PR, there are a few things you can do to make
sure it goes smoothly:

- [ ] Make sure to open a GitHub issue as a bug/feature request before
writing your code! That way we can discuss the change, evaluate designs,
and agree on the general idea
  - [x] Ensure the tests (`melos run test`)
- [x] Ensure the analyzer and formatter pass (`melos run format` to
automatically apply formatting)
- [ ] Appropriate docs were updated (if necessary)